Repository aeternity/aepp-sdk-elixir, pull requests merged in 2019-05, with the labels that each got.

#43 Setup own Aeternity node in Travis CI
  .travis.yml
  aeternity.yaml
  apps/utils/test/test_utils.ex
  apps/utils/test/transaction_util_test.exs
Labels: enhancement

#50 Fee calculation and documentation adjustments
  apps/core/lib/client.ex
  apps/core/lib/name.ex
  apps/utils/lib/transaction.ex
Labels: bug, enhancement, invalid

#53 Fixed fee calculation
  aeternity.yaml
  apps/core/lib/account.ex
  apps/core/lib/contract.ex
  apps/core/lib/name.ex
  apps/core/lib/oracle.ex
  apps/core/test/core_oracle_test.exs
  apps/utils/lib/governance.ex
  apps/utils/lib/transaction.ex
Labels: bug, enhancement

#54 Added tests for Naming system
  apps/core/lib/name.ex
  apps/core/test/naming_test.exs
  apps/utils/test/test_utils.ex
Labels: enhancement

#65 Removed fee from tests
  apps/core/lib/contract.ex
  apps/core/lib/name.ex
  apps/core/test/core_contract_test.exs
  apps/core/test/core_oracle_test.exs
  apps/utils/lib/governance.ex
  apps/utils/lib/transaction.ex
  apps/utils/test/transaction_util_test.exs
Labels: enhancement
